name: EPUB/PDF → Journaling PDF (keep all links)

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: "Path to a PDF already in this repo (e.g., bsb.pdf)"
        required: true
        default: "bsb.pdf"
      right_margin_in:
        description: "Right margin width (inches)"
        required: true
        default: "3.0"
      divider:
        description: "Draw divider line (yes/no)"
        required: true
        default: "yes"
      home_hotspot:
        description: "Add Home hotspot (yes/no)"
        required: true
        default: "yes"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PyMuPDF
        run: pip install --quiet pymupdf

      - name: Make journaling version
        env:
          SRC_PDF: ${{ inputs.pdf_path }}
          RIGHT_IN: ${{ inputs.right_margin_in }}
          DIVIDER: ${{ inputs.divider }}
          HOME: ${{ inputs.home_hotspot }}
        run: python3 tools/add_journal.py

      - uses: actions/upload-artifact@v4
        with:
          name: journaling-pdf
          path: journaling.pdf
          if-no-files-found: error
