name: epub_to_journaling_pdf

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF in this repo (e.g., bsb.pdf)'
        required: true
        default: 'bsb.pdf'
      right_margin_in:
        description: 'Right journal margin in inches'
        required: true
        default: '3.0'
      divider:
        description: 'Draw divider line? yes/no'
        required: true
        default: 'yes'
      home_hotspot:
        description: 'Add Home hotspot? yes/no'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install pymupdf

      - name: Add journaling margin
        shell: bash
        env:
