name: epub_pdf_to_journaling
on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: "Path to a PDF in this repo (e.g., bsb.pdf)"
        required: true
        default: "bsb.pdf"
      right_margin_in:
        description: "Right margin width in inches"
        required: true
        default: "3.0"
      divider:
        description: "Draw divider line (yes/no)"
        required: true
        default: "yes"
      home_hotspot:
        description: "Add Home hotspot (yes/no)"
        required: true
        default: "yes"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install --quiet pymupdf

      - name: Write script to file
        run: |
          mkdir -p tools
          printf "%s\n" \
"import os, sys, fitz" \
"src = os.environ.get('SRC_PDF','bsb.pdf')" \
"right_in = float(os.environ.get('RIGHT_IN','3.0'))" \
"add_div = os.environ.get('DIVIDER','yes').lower()=='yes'" \
"add_home = os.environ.get('HOME','yes').lower()=='yes'" \
"margin = int(right_in*72)" \
"if not os.path.exists(src):" \
"    print('ERROR: missing', src, file=sys.stderr); sys.exit(2)" \
"doc = fitz.open(src)" \
"for p in doc:" \
"    r = p.rect" \
"    p.set_mediabox(fitz.Rect(r.x0, r.y0, r.x1 + margin, r.y1))" \
"    if add_div:" \
"        p.draw_line((r.x1, r.y0+12), (r.x1, r.y1-12), color=(0,0,0), width=0.5)" \
"    if add_home:" \
"        p.insert_text((r.x0+18, r.y0+22), 'Home', fontsize=8, color=(0.2,0.2,0.2))" \
"        p.insert_link({'kind': fitz.LINK_GOTO, 'from': fitz.Rect(r.x0+12, r.y0+10, r.x0+70, r.y0+28), 'page': 0})" \
"doc.save('journaling.pdf')" \
"Wrote='journaling.pdf'" \
          > tools/add_journal.py

      - name: Run journaling script
        env:
          SRC_PDF: ${{ inputs.pdf_path }}
          RIGHT_IN: ${{ inputs.right_margin_in }}
          DIVIDER: ${{ inputs.divider }}
          HOME: ${{ inputs.home_hotspot }}
        run: python3 tools/add_journal.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: journaling-pdf
          path: journaling.pdf
          if-no-files-found: error
