name: Add Journaling Gutter (keep links)

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: "Path to the input PDF in this repo (e.g., source.pdf or input/source.pdf)"
        required: true
        default: source.pdf
      right_margin_in:
        description: "Right journal margin (inches)"
        required: true
        default: "3"
      orientation:
        description: "portrait or landscape (landscape rotates pages; margin becomes right side visually)"
        required: true
        default: portrait

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyMuPDF
        run: pip install --quiet pymupdf

      - name: Add journaling gutter + hotspots (links preserved)
        env:
          PDF_PATH: ${{ inputs.pdf_path }}
          RIGHT_MARGIN_IN: ${{ inputs.right_margin_in }}
          ORIENTATION: ${{ inputs.orientation }}
        run: python add_journal.py

      - name: Upload finished PDF
        uses: actions/upload-artifact@v4
        with:
          name: journaling-pdf
          path: output/journaling.pdf
          if-no-files-found: error
 
