name: EPUB → Journaling PDF (keep links)

on:
  workflow_dispatch:
    inputs:
      epub_path:
        description: "Path to EPUB in repo (e.g., 'bsb 2.epub' or 'bsb.epub')"
        required: true
        default: "bsb 2.epub"
      right_margin_in:
        description: "Right journaling margin (inches)"
        required: true
        default: "3.0"
      paper_size:
        description: "letter or a4"
        required: true
        default: "letter"
      base_font_pt:
        description: "Base font size (pt)"
        required: true
        default: "11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Calibre (ebook-convert)
        run: |
          sudo -v
          curl -L https://download.calibre-ebook.com/linux-installer.py | sudo -E python3 -

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Python deps
        run: pip install --quiet pymupdf

      - name: Copy & validate EPUB
        run: |
          mkdir -p work
          cp "${{ inputs.epub_path }}" "work/book.epub"
          python3 - <<'PY'
import sys, zipfile
p = "work/book.epub"
try:
    zipfile.ZipFile(p).testzip()
    print("EPUB OK:", p)
except Exception as e:
    print("ERROR:", e); sys.exit(1)
PY

      - name: Convert EPUB → PDF (preserve links/TOC)
        run: |
          ebook-convert "work/book.epub" "work/base.pdf" \
            --paper-size "${{ inputs.paper_size }}" \
            --margin-left 54 --margin-right 54 --margin-top 54 --margin-bottom 54 \
            --pdf-use-document-metadata --embed-all-fonts --pdf-add-toc \
            --base-font-size "${{ inputs.base_font_pt }}"
          ls -lh work/base.pdf

      - name: Add journaling gutter (expand page; keep links)
        run: |
          python3 scripts/add_journal.py \
            --in "work/base.pdf" \
            --out "work/journaling.pdf" \
            --right-in "${{ inputs.right_margin_in }}"
          ls -lh work/journaling.pdf

      - name: Upload finished PDF
        uses: actions/upload-artifact@v4
        with:
          name: journaling-pdf
          path: work/journaling.pdf
          if-no-files-found: error
